import type { Locale } from "./i18n";

type Guide = {
  title: string;
  pitch: string;
  openBot: string;
  whatTitle: string;
  what: string;
  whyTitle: string;
  whyLead: string;
  why: [string, string][];
  howTitle: string;
  how: string[];
  assistantTitle: string;
  assistant: string[];
  cmdTitle: string;
  cmds: [string, string][];
  sectionsTitle: string;
  lifehacksTitle: string;
  lifehacks: string[];
  privacyTitle: string;
  privacy: string;
};

const G: Record<Locale, Guide> = {
  ru: {
    title: "Инструкция",
    pitch: "LIFE OS — твоя личная операционная система жизни. Ты говоришь — AI сохраняет, понимает и пишет твою Книгу жизни.",
    openBot: "Открыть бота в Telegram",
    whatTitle: "Что это",
    what: "Это дневник нового поколения. Каждый день ты в пару касаний рассказываешь, что произошло, а AI превращает это в структурированную историю: категории, теги, настроение, инсайты, задачи, люди и проекты — и со временем строит карту твоей жизни.",
    whyTitle: "Чем мы отличаемся от ChatGPT",
    whyLead: "Мы не «умнее» ChatGPT — внутри тот же класс AI. Мы делаем то, ради чего его никто не открывает: без усилий записываем и понимаем именно твою жизнь.",
    why: [
      ["Запись без усилий", "Просто голосовое в Telegram, который и так открыт. ChatGPT нужно открыть и продумать запрос — так каждый день делать не будешь, а привычка решает всё."],
      ["Помнит твою жизнь", "Всё копится в структурированный архив: категории, настроение, люди, проекты, годы. Чаты ChatGPT разрозненны и забываются."],
      ["Понимает во времени", "«Когда я был счастливее всего?», «что влияло на здоровье?» — ответ из всей твоей истории. У ChatGPT её просто нет."],
      ["Это про тебя, а не про вопросы", "Дашборд, Биограф, Книга жизни, Зеркало жизни — целый продукт об одном: понять и сохранить твою жизнь."],
    ],
    howTitle: "Как пользоваться",
    how: [
      "🎤 Наговори голосовое или напиши текст боту в Telegram — о чём угодно: день, мысли, здоровье, идеи, тренировки, семья.",
      "🧠 AI распознает речь, разложит по полочкам и выделит главное.",
      "🌐 Открой веб-версию (кнопка в боте) — там дневник, аналитика, поиск и AI-Биограф.",
    ],
    assistantTitle: "Бот-ассистент",
    assistant: [
      "Просто задай вопрос — бот сам поймёт, что это вопрос, и ответит по твоему дневнику. Например: «какие у меня цели?», «что я писал про спорт?», «когда я последний раз болел?».",
      "Расскажешь про день — бот сохранит это как запись. Если сомневается — сохраняет, чтобы не потерять мысль.",
      "Хочешь наверняка: /ask … — точно задать вопрос, /save … — точно сохранить запись.",
    ],
    cmdTitle: "Команды бота",
    cmds: [
      ["/start", "приветствие и твоя личная ссылка на сайт"],
      ["/link", "получить ссылку на веб-дневник заново"],
      ["/invite", "пригласить друга"],
      ["/demo", "посмотреть приветственный диалог"],
      ["/ask …", "спросить ассистента (или просто задай вопрос — бот поймёт сам)"],
      ["/save …", "сохранить как запись принудительно"],
    ],
    sectionsTitle: "Разделы",
    lifehacksTitle: "Лайфхаки",
    lifehacks: [
      "Пиши каждый день хотя бы пару строк — привычка и стрик 🔥 важнее объёма.",
      "Голос быстрее текста: 30 секунд на ходу = полноценная запись.",
      "Упоминай имена и проекты — так AI строит связи (Life Intelligence) и карту жизни.",
      "Раз в неделю спроси Биографа: «как прошла моя неделя?» или «расскажи историю проекта».",
      "Плохой день — тоже запись. Именно из них потом видно, что влияет на настроение.",
      "Не идеальничай — наговаривай как есть, AI сам причешет формулировки.",
      "В вебе тоже можно наговаривать голосом — нажми 🎤 рядом с «Добавить» на главной.",
      "Загляни в «Лабораторию»: проверь гипотезу AI экспериментом (напр. ложиться раньше) — и увидишь честный итог «до/после».",
      "В боте можно просто задать вопрос — он сам поймёт, ответить или сохранить (а ещё кнопки и команда /ask).",
      "Добавь LIFE OS на экран «Домой» — откроется как приложение. На iPhone: в Safari «Поделиться» → «На экран «Домой»». На Android: в Chrome меню ⋮ → «Установить приложение» (или «Добавить на главный экран»).",
      "В разделе «Профиль» можно поставить PIN-код на вход — дневник под замком, даже если у кого-то твоя ссылка. Сброс — командой /resetpin в боте.",
      "Нашёл полезный пост или видео — кинь ссылку (Instagram/YouTube/TikTok) боту: AI сохранит суть в «Базу знаний». А фото и документы (чек, гарантия, момент) идут в «Память». Потом всё это можно искать и спрашивать.",
      "Скоро день рождения? Кидай ссылки на желания боту (/wish) или в раздел «Вишлист» — подтянутся фото и цена. Нажми «Поделиться» и отправь список друзьям: они тайно «забронируют» подарок, и двое не подарят одно и то же.",
      "Ведёшь книги? В разделе «Книги» добавляй их поиском, по фото обложки/штрих-кода (распознает AI) или импортом из Goodreads/StoryGraph. Ставь оценку и мини-ревью «зашла или нет», а AI подскажет, что почитать дальше.",
      "Нужно что-то передать другу из LIFE OS — скажи боту голосом: «передай Ане, что опоздаю». Или задай прозвище (/nick @имя Котик) и пиши «передай Котику …». Ему придёт сообщение с твоей подписью.",
    ],
    privacyTitle: "Приватность",
    privacy: "Дневник виден только тебе. Команда не читает твои записи — для аналитики видны лишь обезличенные цифры. AI обрабатывает текст только ради твоих резюме и ответов и не используется для обучения моделей. Данные шифруются, удалить всё можно в любой момент.",
  },
  en: {
    title: "Guide",
    pitch: "LIFE OS is your personal operating system for life. You speak — AI saves it, understands it and writes your Book of Life.",
    openBot: "Open the bot in Telegram",
    whatTitle: "What it is",
    what: "A next-generation diary. Each day you tell it what happened in a couple of taps, and AI turns it into a structured story: categories, tags, mood, insights, tasks, people and projects — and over time builds a map of your life.",
    whyTitle: "How we're different from ChatGPT",
    whyLead: "We're not “smarter” than ChatGPT — same class of AI inside. We do what no one opens it for: effortlessly capture and understand your own life.",
    why: [
      ["Capture with zero effort", "Just a voice note in Telegram you already have open. ChatGPT needs you to open it and craft a prompt — you won't do that every day, and the habit is everything."],
      ["Remembers your life", "Everything builds into a structured archive: categories, mood, people, projects, years. ChatGPT chats are scattered and forgotten."],
      ["Understands over time", "“When was I happiest?”, “what affected my health?” — answered from your whole history. ChatGPT simply doesn't have it."],
      ["About you, not questions", "Dashboard, Biographer, Book of Life, Life Mirror — a whole product about one thing: understanding and keeping your life."],
    ],
    howTitle: "How to use it",
    how: [
      "🎤 Send a voice note or text to the Telegram bot — anything: your day, thoughts, health, ideas, workouts, family.",
      "🧠 AI transcribes it, sorts it out and extracts what matters.",
      "🌐 Open the web version (button in the bot) — diary, analytics, search and the AI Biographer.",
    ],
    assistantTitle: "Assistant",
    assistant: [
      "Just ask a question — the bot recognizes it's a question and answers from your diary. E.g. “what are my goals?”, “what did I write about sport?”, “when was I last sick?”.",
      "Tell it about your day — it saves that as an entry. When unsure, it saves, so no thought is lost.",
      "Want to be sure: /ask … to ask for certain, /save … to save for certain.",
    ],
    cmdTitle: "Bot commands",
    cmds: [
      ["/start", "welcome and your personal link"],
      ["/link", "get your web diary link again"],
      ["/invite", "invite a friend"],
      ["/demo", "replay the welcome dialog"],
      ["/ask …", "ask the assistant (or just ask — the bot figures it out)"],
      ["/save …", "force-save as an entry"],
    ],
    sectionsTitle: "Sections",
    lifehacksTitle: "Tips & tricks",
    lifehacks: [
      "Write a few lines every day — the habit and the streak 🔥 matter more than length.",
      "Voice is faster than typing: 30 seconds on the go = a full entry.",
      "Mention names and projects — that's how AI builds connections (Life Intelligence) and your life map.",
      "Once a week, ask the Biographer: “how was my week?” or “tell the story of my project”.",
      "A bad day is an entry too. Those reveal what actually affects your mood.",
      "Don't aim for perfect — just talk; AI will polish the wording.",
      "On the web you can record by voice too — tap 🎤 next to “Add” on the home screen.",
      "Try the Lab: test an AI hypothesis with an experiment (e.g. earlier bedtime) and see an honest before/after.",
      "In the bot you can just ask a question — it figures out whether to answer or save (plus buttons and /ask).",
      "Add LIFE OS to your home screen — it opens like an app. On iPhone: in Safari tap Share → “Add to Home Screen”. On Android: in Chrome tap menu ⋮ → “Install app” (or “Add to Home screen”).",
      "In “Profile” you can set a PIN for web access — your diary stays locked even if someone has your link. Reset it with /resetpin in the bot.",
      "Found a useful post or video — send the link (Instagram/YouTube/TikTok) to the bot: AI saves the gist to your “Knowledge Base”. Photos and documents (receipt, warranty, a moment) go to “Memory”. Then search and ask all of it.",
      "Birthday coming up? Send wish links to the bot (/wish) or to the “Wishlist” section — photo and price get pulled in. Hit “Share” and send the list to friends: they secretly reserve a gift, so no two people buy the same thing.",
      "Track your reading? In “Books”, add titles by search, by a photo of the cover/barcode (AI recognizes it), or by importing from Goodreads/StoryGraph. Rate them, write a quick “loved it or not” review, and let AI suggest what to read next.",
      "Need to pass something to a LIFE OS friend — just tell the bot by voice: “tell Anna I'll be late”. Or set a nickname (/nick @name Kitty) and write “tell Kitty …”. They get the message signed with your name.",
    ],
    privacyTitle: "Privacy",
    privacy: "Only you can see your diary. The team doesn't read your entries — analytics show only anonymous numbers. AI processes the text only for your summaries and answers, and isn't used to train models. Data is encrypted; you can delete everything anytime.",
  },
  uk: {
    title: "Інструкція",
    pitch: "LIFE OS — твоя особиста операційна система життя. Ти говориш — AI зберігає, розуміє й пише твою Книгу життя.",
    openBot: "Відкрити бота в Telegram",
    whatTitle: "Що це",
    what: "Щоденник нового покоління. Щодня ти в кілька дотиків розповідаєш, що сталося, а AI перетворює це на структуровану історію: категорії, теги, настрій, інсайти, завдання, люди й проєкти — і з часом будує карту твого життя.",
    whyTitle: "Чим ми відрізняємось від ChatGPT",
    whyLead: "Ми не «розумніші» за ChatGPT — усередині той самий клас AI. Ми робимо те, заради чого його ніхто не відкриває: без зусиль записуємо й розуміємо саме твоє життя.",
    why: [
      ["Запис без зусиль", "Просто голосове в Telegram, який і так відкритий. ChatGPT треба відкрити й продумати запит — щодня так не робитимеш, а звичка вирішує все."],
      ["Пам'ятає твоє життя", "Усе накопичується у структурований архів: категорії, настрій, люди, проєкти, роки. Чати ChatGPT розрізнені й забуваються."],
      ["Розуміє у часі", "«Коли я був найщасливішим?», «що впливало на здоров'я?» — відповідь з усієї твоєї історії. У ChatGPT її просто немає."],
      ["Про тебе, а не про питання", "Дашборд, Біограф, Книга життя, Дзеркало життя — цілий продукт про одне: зрозуміти й зберегти твоє життя."],
    ],
    howTitle: "Як користуватися",
    how: [
      "🎤 Надішли голосове або текст боту в Telegram — про що завгодно: день, думки, здоров'я, ідеї, тренування, сім'я.",
      "🧠 AI розпізнає мовлення, розкладе по полицях і виділить головне.",
      "🌐 Відкрий веб-версію (кнопка в боті) — щоденник, аналітика, пошук і AI-Біограф.",
    ],
    assistantTitle: "Бот-асистент",
    assistant: [
      "Просто постав питання — бот сам зрозуміє, що це питання, і відповість за твоїм щоденником. Напр.: «які в мене цілі?», «що я писав про спорт?».",
      "Розкажеш про день — бот збереже це як запис. Якщо сумнівається — зберігає, щоб не втратити думку.",
      "Хочеш напевно: /ask … — точно запитати, /save … — точно зберегти запис.",
    ],
    cmdTitle: "Команди бота",
    cmds: [
      ["/start", "привітання і твоє особисте посилання"],
      ["/link", "отримати посилання на веб-щоденник знову"],
      ["/invite", "запросити друга"],
      ["/demo", "переглянути привітальний діалог"],
      ["/ask …", "запитати асистента (або просто постав питання — бот зрозуміє)"],
      ["/save …", "примусово зберегти як запис"],
    ],
    sectionsTitle: "Розділи",
    lifehacksTitle: "Лайфхаки",
    lifehacks: [
      "Пиши щодня хоча б кілька рядків — звичка і стрик 🔥 важливіші за обсяг.",
      "Голос швидший за текст: 30 секунд на ходу = повноцінний запис.",
      "Згадуй імена та проєкти — так AI будує зв'язки (Life Intelligence) і карту життя.",
      "Раз на тиждень запитай Біографа: «як минув мій тиждень?».",
      "Поганий день — теж запис. Саме з них видно, що впливає на настрій.",
      "Не намагайся ідеально — говори як є, AI причеше формулювання.",
      "У вебі теж можна наговорювати голосом — натисни 🎤 біля «Додати» на головній.",
      "Зазирни в «Лабораторію»: перевір гіпотезу AI експериментом — і побачиш чесний підсумок «до/після».",
      "У боті можна просто поставити питання — він сам зрозуміє, відповісти чи зберегти (а ще кнопки й /ask).",
      "Додай LIFE OS на екран «Додому»: у Safari натисни «Поділитися» → «На екран Додому» — відкриється як застосунок.",
      "У розділі «Профіль» можна поставити PIN на вхід — щоденник під замком, навіть якщо в когось твоє посилання. Скидання — командою /resetpin у боті.",
      "Знайшов корисний пост чи відео — кинь посилання (Instagram/YouTube) боту: AI збереже суть у «Базу знань». А фото й документи (чек, гарантія, момент) ідуть у «Пам'ять». Потім усе це можна шукати й питати.",
    ],
    privacyTitle: "Приватність",
    privacy: "Щоденник бачиш лише ти. Команда не читає твої записи — в аналітиці лише знеособлені цифри. AI обробляє текст тільки заради твоїх резюме й відповідей і не використовується для навчання моделей. Дані шифруються, видалити все можна будь-коли.",
  },
  fr: {
    title: "Guide",
    pitch: "LIFE OS est ton système d'exploitation personnel pour la vie. Tu parles — l'IA sauvegarde, comprend et écrit ton Livre de vie.",
    openBot: "Ouvrir le bot dans Telegram",
    whatTitle: "Qu'est-ce que c'est",
    what: "Un journal nouvelle génération. Chaque jour tu racontes ta journée en quelques gestes, et l'IA en fait une histoire structurée : catégories, tags, humeur, insights, tâches, personnes et projets — et au fil du temps, une carte de ta vie.",
    whyTitle: "En quoi nous différons de ChatGPT",
    whyLead: "On n'est pas « plus intelligents » que ChatGPT — même classe d'IA à l'intérieur. On fait ce pour quoi personne ne l'ouvre : capturer et comprendre ta propre vie sans effort.",
    why: [
      ["Capture sans effort", "Juste une note vocale dans Telegram déjà ouvert. ChatGPT demande de l'ouvrir et de formuler — tu ne le feras pas chaque jour, et l'habitude fait tout."],
      ["Se souvient de ta vie", "Tout s'accumule en archive structurée : catégories, humeur, personnes, projets, années. Les chats ChatGPT sont éparpillés et oubliés."],
      ["Comprend dans le temps", "« Quand étais-je le plus heureux ? », « qu'est-ce qui affectait ma santé ? » — répondu depuis toute ton histoire. ChatGPT ne l'a pas."],
      ["Sur toi, pas des questions", "Tableau de bord, Biographe, Livre de vie, Miroir de vie — un produit entier pour une chose : comprendre et garder ta vie."],
    ],
    howTitle: "Comment l'utiliser",
    how: [
      "🎤 Envoie une note vocale ou un texte au bot Telegram — tout : ta journée, tes pensées, ta santé, tes idées, le sport, la famille.",
      "🧠 L'IA transcrit, organise et extrait l'essentiel.",
      "🌐 Ouvre la version web (bouton dans le bot) — journal, analytique, recherche et le Biographe IA.",
    ],
    assistantTitle: "Assistant",
    assistant: [
      "Pose simplement une question — le bot comprend que c'est une question et répond à partir de ton journal. Ex. : « quels sont mes objectifs ? », « qu'ai-je écrit sur le sport ? ».",
      "Raconte ta journée — il l'enregistre comme une entrée. En cas de doute, il enregistre, pour ne rien perdre.",
      "Pour être sûr : /ask … pour demander, /save … pour enregistrer.",
    ],
    cmdTitle: "Commandes du bot",
    cmds: [
      ["/start", "accueil et ton lien personnel"],
      ["/link", "récupérer ton lien web"],
      ["/invite", "inviter un ami"],
      ["/demo", "revoir le dialogue d'accueil"],
      ["/ask …", "demander à l'assistant (ou pose ta question — le bot comprend)"],
      ["/save …", "forcer l'enregistrement comme entrée"],
    ],
    sectionsTitle: "Sections",
    lifehacksTitle: "Astuces",
    lifehacks: [
      "Écris quelques lignes chaque jour — l'habitude et la série 🔥 comptent plus que la longueur.",
      "La voix est plus rapide : 30 secondes en chemin = une entrée complète.",
      "Mentionne les noms et les projets — ainsi l'IA crée des liens (Life Intelligence) et ta carte de vie.",
      "Une fois par semaine, demande au Biographe : « comment s'est passée ma semaine ? ».",
      "Une mauvaise journée est aussi une entrée. Elles révèlent ce qui influence ton humeur.",
      "Ne vise pas la perfection — parle simplement, l'IA peaufine.",
      "Sur le web aussi tu peux dicter à la voix — touche 🎤 à côté de « Ajouter » sur l'accueil.",
      "Essaie le Labo : teste une hypothèse de l'IA par une expérience et vois un avant/après honnête.",
      "Dans le bot tu peux juste poser une question — il décide de répondre ou d'enregistrer (boutons et /ask aussi).",
      "Ajoute LIFE OS à l'écran d'accueil — il s'ouvre comme une app. Sur iPhone : dans Safari, Partager → « Sur l'écran d'accueil ». Sur Android : dans Chrome, menu ⋮ → « Installer l'application » (ou « Ajouter à l'écran d'accueil »).",
      "Dans « Profil », tu peux définir un PIN pour l'accès web — ton journal reste verrouillé même si quelqu'un a ton lien. Réinitialise-le avec /resetpin dans le bot.",
      "Tu as trouvé un post ou une vidéo utile — envoie le lien (Instagram/YouTube) au bot : l'IA en garde l'essentiel dans ta « Base de connaissances ». Les photos et documents (reçu, garantie, un moment) vont dans « Mémoire ». Ensuite, recherche et interroge tout ça.",
    ],
    privacyTitle: "Confidentialité",
    privacy: "Toi seul vois ton journal. L'équipe ne lit pas tes entrées — les stats ne montrent que des chiffres anonymes. L'IA traite le texte seulement pour tes résumés et réponses, sans servir à entraîner des modèles. Données chiffrées ; tu peux tout supprimer à tout moment.",
  },
  es: {
    title: "Guía",
    pitch: "LIFE OS es tu sistema operativo personal para la vida. Tú hablas — la IA lo guarda, lo entiende y escribe tu Libro de la vida.",
    openBot: "Abrir el bot en Telegram",
    whatTitle: "Qué es",
    what: "Un diario de nueva generación. Cada día cuentas lo que pasó en un par de toques, y la IA lo convierte en una historia estructurada: categorías, etiquetas, estado de ánimo, ideas clave, tareas, personas y proyectos — y con el tiempo construye un mapa de tu vida.",
    whyTitle: "En qué nos diferenciamos de ChatGPT",
    whyLead: "No somos «más listos» que ChatGPT — dentro llevamos el mismo tipo de IA. Hacemos lo que nadie lo abre para hacer: capturar y entender tu propia vida sin esfuerzo.",
    why: [
      ["Registro sin esfuerzo", "Solo una nota de voz en el Telegram que ya tienes abierto. ChatGPT te obliga a abrirlo y redactar un prompt — no lo harás todos los días, y el hábito lo es todo."],
      ["Recuerda tu vida", "Todo se acumula en un archivo estructurado: categorías, estado de ánimo, personas, proyectos, años. Los chats de ChatGPT están dispersos y se olvidan."],
      ["Entiende con el tiempo", "«¿Cuándo fui más feliz?», «¿qué afectaba mi salud?» — respondido con toda tu historia. ChatGPT simplemente no la tiene."],
      ["Se trata de ti, no de preguntas", "Panel, Biógrafo, Libro de la vida, Espejo de la vida — todo un producto centrado en una sola cosa: entender y conservar tu vida."],
    ],
    howTitle: "Cómo usarlo",
    how: [
      "🎤 Envía una nota de voz o un texto al bot de Telegram — sobre lo que sea: tu día, pensamientos, salud, ideas, entrenamientos, familia.",
      "🧠 La IA transcribe, organiza y extrae lo importante.",
      "🌐 Abre la versión web (botón en el bot) — diario, analítica, búsqueda y el Biógrafo IA.",
    ],
    assistantTitle: "Asistente",
    assistant: [
      "Simplemente haz una pregunta — el bot reconoce que es una pregunta y responde con base en tu diario. Por ejemplo: «¿cuáles son mis metas?», «¿qué escribí sobre deporte?», «¿cuándo fue la última vez que estuve enfermo?».",
      "Cuéntale sobre tu día — el bot lo guarda como una entrada. Si tiene dudas, lo guarda igual, para no perder ninguna idea.",
      "Si quieres estar seguro: /ask … para preguntar sin dudas, /save … para guardar sin dudas.",
    ],
    cmdTitle: "Comandos del bot",
    cmds: [
      ["/start", "bienvenida y tu enlace personal"],
      ["/link", "obtener de nuevo el enlace a tu diario web"],
      ["/invite", "invitar a un amigo"],
      ["/demo", "ver de nuevo el diálogo de bienvenida"],
      ["/ask …", "preguntar al asistente (o simplemente pregunta — el bot lo entiende)"],
      ["/save …", "forzar el guardado como entrada"],
    ],
    sectionsTitle: "Secciones",
    lifehacksTitle: "Trucos y consejos",
    lifehacks: [
      "Escribe unas líneas cada día — el hábito y la racha 🔥 importan más que la extensión.",
      "La voz es más rápida que escribir: 30 segundos de camino = una entrada completa.",
      "Menciona nombres y proyectos — así la IA construye conexiones (Life Intelligence) y tu mapa de vida.",
      "Una vez por semana, pregúntale al Biógrafo: «¿cómo fue mi semana?» o «cuéntame la historia de mi proyecto».",
      "Un mal día también es una entrada. Precisamente de esos se ve qué afecta tu estado de ánimo.",
      "No busques la perfección — simplemente habla, la IA pulirá la redacción.",
      "En la web también puedes grabar por voz — toca 🎤 junto a «Añadir» en el inicio.",
      "Prueba el «Laboratorio»: pon a prueba una hipótesis de la IA con un experimento (p. ej., acostarte más temprano) y verás un antes/después honesto.",
      "En el bot puedes simplemente hacer una pregunta — él decide si responder o guardar (además hay botones y el comando /ask).",
      "Añade LIFE OS a tu pantalla de inicio — se abrirá como una app. En iPhone: en Safari toca Compartir → «Añadir a pantalla de inicio». En Android: en Chrome, menú ⋮ → «Instalar aplicación» (o «Añadir a pantalla de inicio»).",
      "En «Perfil» puedes poner un PIN para el acceso web — tu diario queda bajo llave aunque alguien tenga tu enlace. Restablécelo con /resetpin en el bot.",
      "¿Encontraste un post o video útil? Envía el enlace (Instagram/YouTube/TikTok) al bot: la IA guarda lo esencial en tu «Base de conocimiento». Las fotos y documentos (recibo, garantía, un momento) van a «Memoria». Después puedes buscar y preguntar sobre todo eso.",
      "¿Se acerca un cumpleaños? Envía enlaces de deseos al bot (/wish) o a la sección «Lista de deseos» — se completarán con foto y precio. Toca «Compartir» y envía la lista a tus amigos: reservarán el regalo en secreto, así nadie repite el mismo obsequio.",
      "¿Llevas un registro de lectura? En «Libros», añádelos buscando, con una foto de la portada/código de barras (la IA lo reconoce) o importando desde Goodreads/StoryGraph. Puntúalos, escribe una mini reseña de «me gustó o no» y deja que la IA te sugiera qué leer después.",
      "¿Necesitas avisarle algo a un amigo de LIFE OS? Dile al bot por voz: «avísale a Ana que llegaré tarde». O ponle un apodo (/nick @nombre Gatita) y escribe «avísale a Gatita …». Le llegará el mensaje firmado con tu nombre.",
    ],
    privacyTitle: "Privacidad",
    privacy: "Solo tú ves tu diario. El equipo no lee tus entradas — la analítica solo muestra cifras anónimas. La IA procesa el texto únicamente para tus resúmenes y respuestas, y no se usa para entrenar modelos. Los datos están cifrados; puedes eliminarlo todo cuando quieras.",
  },
};

export function guide(locale: Locale): Guide {
  return G[locale] || G.ru;
}
