import type { Locale } from "./i18n";

const H: Record<Locale, Record<string, string>> = {
  ru: {
    today: "Главный экран: твои показатели и записи за сегодня. Можно добавить запись прямо здесь или голосом в Telegram.",
    diary: "Все записи по датам. Нажми на запись — увидишь полный AI-разбор.",
    tasks: "Все твои задачи из записей в одном месте. Отмечай выполненные галочкой.",
    wellness: "Здоровье, энергия, спорт и питание — всё о теле в одном месте.",
    plans: "Цели, задачи и идеи вместе — планируй и ничего не теряй.",
    finance: "Простой учёт денег: записывай доходы и расходы, выбирай категорию — и сразу видишь баланс месяца и на что уходят деньги.",
    health: "Сон, вес, самочувствие и тренды. Наполняется, когда упоминаешь здоровье в записях.",
    analytics: "AI находит закономерности, открытия и историю твоей жизни — каждый день что-то новое о тебе.",
    lab: "AI замечает закономерности и предлагает гипотезы — а ты проверяешь их экспериментами над своей жизнью.",
    insights: "Все важные мысли и осознания, которые AI выделил из твоих записей.",
    people: "Люди из записей: сколько раз упомянуты и в каких записях.",
    projects: "Твои проекты, собранные из записей, со всеми связанными заметками.",
    biographer: "Спроси свою жизнь — AI соберёт ответ-историю из всех твоих записей. Например: «Расскажи историю проекта» или «Как менялось моё здоровье?».",
    wishlist: "Список желаний: вставь ссылку на товар — подтянем фото, название и цену. Поделись с друзьями, они тайно «забронируют» подарок — сюрприз сохранится.",
    books: "Твоя библиотека: что читаешь, хочешь и прочитал. Оценка, мини-ревью «зашла или нет», заметки и цитаты. Цель года, AI-советы и публичная страница для друзей.",
    intelligence: "AI находит причины, последствия и связи этой записи с другими — строго по твоим данным, без выдумок.",
    goals: "Цели на год с прогрессом. Добавляй цель и двигай ползунок по мере выполнения.",
    lifebook: "AI собирает каждый месяц твоей жизни в главу — с темами и связным рассказом.",
    knowledge: "Личная база знаний. Пришли боту ссылку на пост/reel Instagram или видео YouTube — AI вытащит суть (заголовок, ключевые мысли, теги) и сохранит сюда. Потом ищи по смыслу и возвращайся к идеям.",
    memory: "Визуальная память. Пришли боту или загрузи фото/документ (чек, гарантия, важный момент) — AI поймёт смысл, извлечёт данные и разложит по категориям. К фото можно добавить заметку голосом.",
    energy: "Как меняется твоя энергия и что её повышает.",
    sport: "Все записи про спорт и тренировки.",
    food: "Записи про питание и еду.",
    family: "Моменты и события с семьёй.",
    places: "Хронология твоих путешествий: поездки с фото и записями тех дней — и мечты, куда хочешь.",
    profile: "Твой личный кабинет: личная ссылка, язык, приватность, выход и удаление аккаунта.",
  },
  en: {
    today: "Your day at a glance: today's metrics and entries. Add an entry here or by voice in Telegram.",
    diary: "All your entries by date. Tap an entry to see the full AI breakdown.",
    tasks: "All your tasks from entries in one place. Tick them off when done.",
    wellness: "Health, energy, sport and food — all about your body in one place.",
    plans: "Goals, tasks and ideas together — plan and lose nothing.",
    finance: "Simple money tracking: log income and expenses, pick a category — and instantly see your monthly balance and where the money goes.",
    health: "Sleep, weight, wellbeing and trends. Fills in as you mention health in entries.",
    analytics: "AI finds patterns, discoveries and the story of your life — something new about you every day.",
    lab: "AI spots patterns and suggests hypotheses — you test them with experiments on your own life.",
    insights: "All the key thoughts and realizations AI extracted from your entries.",
    people: "People from your entries: how often mentioned and in which entries.",
    projects: "Your projects gathered from entries, with all related notes.",
    biographer: "Ask your life — AI weaves an answer from all your entries. E.g. “Tell the story of my project” or “How did my health change?”.",
    wishlist: "Wishlist: paste a product link — we'll pull the photo, title and price. Share with friends; they secretly reserve a gift so the surprise stays.",
    books: "Your library: what you're reading, want to read and have read. Rating, a quick “loved it or not” review, notes and quotes. Year goal, AI picks and a public page for friends.",
    intelligence: "AI finds causes, consequences and links of this entry to others — strictly from your data, no invention.",
    goals: "Yearly goals with progress. Add a goal and move the slider as you advance.",
    lifebook: "AI turns each month of your life into a chapter — themes and a flowing story.",
    knowledge: "Your personal knowledge base. Send the bot an Instagram post/reel or YouTube link — AI extracts the gist (title, key points, tags) and saves it here. Then search by meaning and revisit ideas.",
    memory: "Visual memory. Send or upload a photo/document (receipt, warranty, a moment) — AI understands it, extracts the details and files it by category. You can add a note by voice.",
    energy: "How your energy changes and what lifts it.",
    sport: "All your entries about sport and workouts.",
    food: "Entries about food and nutrition.",
    family: "Moments and events with your family.",
    places: "Your travel timeline: trips with photos and entries from those days — plus dream destinations.",
    profile: "Your account: personal link, language, privacy, log out and delete account.",
  },
  uk: {
    today: "Головний екран: твої показники та записи за сьогодні. Можна додати запис тут або голосом у Telegram.",
    diary: "Усі записи за датами. Натисни на запис — побачиш повний AI-розбір.",
    tasks: "Усі твої завдання із записів в одному місці. Познач виконані галочкою.",
    wellness: "Здоров'я, енергія, спорт і харчування — все про тіло в одному місці.",
    plans: "Цілі, завдання та ідеї разом — плануй і нічого не втрачай.",
    finance: "Простий облік грошей: записуй доходи й витрати, обирай категорію — і одразу бачиш баланс місяця та на що йдуть гроші.",
    health: "Сон, вага, самопочуття та тренди. Наповнюється, коли згадуєш здоров'я в записах.",
    analytics: "AI знаходить закономірності, відкриття та історію твого життя — щодня щось нове про тебе.",
    lab: "AI помічає закономірності й пропонує гіпотези — а ти перевіряєш їх експериментами над своїм життям.",
    insights: "Усі важливі думки та усвідомлення, які AI виділив із твоїх записів.",
    people: "Люди з записів: скільки разів згадані та в яких записах.",
    projects: "Твої проєкти, зібрані із записів, з усіма пов'язаними нотатками.",
    biographer: "Запитай своє життя — AI збере відповідь-історію з усіх твоїх записів. Напр.: «Розкажи історію проєкту».",
    wishlist: "Список бажань: встав посилання на товар — підтягнемо фото, назву й ціну. Поділись із друзями, вони таємно «забронюють» подарунок — сюрприз збережеться.",
    books: "Твоя бібліотека: що читаєш, хочеш і прочитав. Оцінка, міні-рецензія «зайшла чи ні», нотатки й цитати. Ціль року, AI-поради та публічна сторінка для друзів.",
    intelligence: "AI знаходить причини, наслідки та зв'язки цього запису з іншими — строго за твоїми даними.",
    goals: "Цілі на рік із прогресом. Додавай ціль і рухай повзунок у міру виконання.",
    lifebook: "AI збирає кожен місяць твого життя у главу — з темами та зв'язною розповіддю.",
    knowledge: "Особиста база знань. Надішли боту посилання на допис/reel Instagram або відео YouTube — AI витягне суть (заголовок, ключові думки, теги) і збереже сюди. Потім шукай за змістом і повертайся до ідей.",
    memory: "Візуальна пам'ять. Надішли або завантаж фото/документ (чек, гарантія, важливий момент) — AI зрозуміє суть, витягне дані й розкладе за категоріями. До фото можна додати нотатку голосом.",
    energy: "Як змінюється твоя енергія і що її підвищує.",
    sport: "Усі записи про спорт і тренування.",
    food: "Записи про харчування та їжу.",
    family: "Моменти й події з сім'єю.",
    places: "Хронологія твоїх подорожей: поїздки з фото і записами тих днів — і мрії, куди хочеш.",
    profile: "Твій особистий кабінет: посилання, мова, приватність, вихід і видалення акаунта.",
  },
  fr: {
    today: "Ta journée en un coup d'œil : indicateurs et entrées du jour. Ajoute une entrée ici ou par la voix dans Telegram.",
    diary: "Toutes tes entrées par date. Touche une entrée pour voir l'analyse IA complète.",
    tasks: "Toutes tes tâches en un seul endroit. Coche-les quand c'est fait.",
    wellness: "Santé, énergie, sport et alimentation — tout sur ton corps au même endroit.",
    plans: "Objectifs, tâches et idées ensemble — planifie sans rien perdre.",
    finance: "Suivi simple de l'argent : note tes revenus et dépenses, choisis une catégorie — et vois aussitôt ton solde du mois et où part l'argent.",
    health: "Sommeil, poids, bien-être et tendances. Se remplit quand tu mentionnes la santé.",
    analytics: "L'IA trouve des schémas, des découvertes et l'histoire de ta vie — du nouveau sur toi chaque jour.",
    lab: "L'IA repère des schémas et propose des hypothèses — tu les testes par des expériences sur ta vie.",
    insights: "Toutes les pensées clés que l'IA a extraites de tes entrées.",
    people: "Les personnes de tes entrées : fréquence et entrées associées.",
    projects: "Tes projets rassemblés depuis les entrées, avec toutes les notes liées.",
    biographer: "Interroge ta vie — l'IA tisse une réponse à partir de toutes tes entrées. Ex. : « Raconte l'histoire de mon projet ».",
    wishlist: "Liste de souhaits : colle un lien produit — on récupère la photo, le titre et le prix. Partage-la ; tes amis réservent un cadeau en secret, la surprise reste.",
    books: "Ta bibliothèque : ce que tu lis, veux lire et as lu. Note, mini-avis « aimé ou pas », notes et citations. Objectif de l'année, suggestions IA et page publique pour tes amis.",
    intelligence: "L'IA trouve causes, conséquences et liens de cette entrée — strictement à partir de tes données.",
    goals: "Objectifs annuels avec progression. Ajoute un objectif et déplace le curseur.",
    lifebook: "L'IA transforme chaque mois de ta vie en chapitre — thèmes et récit fluide.",
    knowledge: "Ta base de connaissances. Envoie au bot un lien Instagram (post/reel) ou YouTube — l'IA en extrait l'essentiel (titre, points clés, tags) et l'enregistre ici. Ensuite, recherche par sens et retrouve tes idées.",
    memory: "Mémoire visuelle. Envoie ou téléverse une photo/document (reçu, garantie, un moment) — l'IA le comprend, en extrait les détails et le classe par catégorie. Tu peux ajouter une note par la voix.",
    energy: "Comment ton énergie évolue et ce qui la booste.",
    sport: "Toutes tes entrées sur le sport.",
    food: "Entrées sur l'alimentation.",
    family: "Moments et événements en famille.",
    places: "La chronologie de tes voyages : séjours avec photos et entrées de ces jours — et tes destinations de rêve.",
    profile: "Ton compte : lien personnel, langue, confidentialité, déconnexion et suppression.",
  },
};

export function hints(locale: Locale): Record<string, string> {
  return H[locale] || H.ru;
}
