import type { Locale } from "./i18n";

const H: Record<Locale, Record<string, string>> = {
  ru: {
    today: "Главный экран: твои показатели и записи за сегодня. Можно добавить запись прямо здесь или голосом в Telegram.",
    diary: "Все записи по датам. Нажми на запись — увидишь полный AI-разбор.",
    tasks: "Все твои задачи из записей в одном месте. Отмечай выполненные галочкой.",
    wellness: "Здоровье, энергия, спорт и питание — всё о теле в одном месте.",
    plans: "Цели, задачи и идеи вместе — планируй и ничего не теряй.",
    health: "Сон, вес, самочувствие и тренды. Наполняется, когда упоминаешь здоровье в записях.",
    analytics: "AI находит закономерности, открытия и историю твоей жизни — каждый день что-то новое о тебе.",
    lab: "AI замечает закономерности и предлагает гипотезы — а ты проверяешь их экспериментами над своей жизнью.",
    insights: "Все важные мысли и осознания, которые AI выделил из твоих записей.",
    people: "Люди из записей: сколько раз упомянуты и в каких записях.",
    projects: "Твои проекты, собранные из записей, со всеми связанными заметками.",
    biographer: "Спроси свою жизнь — AI соберёт ответ-историю из всех твоих записей. Например: «Расскажи историю проекта» или «Как менялось моё здоровье?».",
    intelligence: "AI находит причины, последствия и связи этой записи с другими — строго по твоим данным, без выдумок.",
    goals: "Цели на год с прогрессом. Добавляй цель и двигай ползунок по мере выполнения.",
    lifebook: "AI собирает каждый месяц твоей жизни в главу — с темами и связным рассказом.",
    energy: "Как меняется твоя энергия и что её повышает.",
    sport: "Все записи про спорт и тренировки.",
    food: "Записи про питание и еду.",
    family: "Моменты и события с семьёй.",
    places: "Места из твоих записей — где ты бывал.",
    profile: "Твой личный кабинет: личная ссылка, язык, приватность, выход и удаление аккаунта.",
  },
  en: {
    today: "Your day at a glance: today's metrics and entries. Add an entry here or by voice in Telegram.",
    diary: "All your entries by date. Tap an entry to see the full AI breakdown.",
    tasks: "All your tasks from entries in one place. Tick them off when done.",
    wellness: "Health, energy, sport and food — all about your body in one place.",
    plans: "Goals, tasks and ideas together — plan and lose nothing.",
    health: "Sleep, weight, wellbeing and trends. Fills in as you mention health in entries.",
    analytics: "AI finds patterns, discoveries and the story of your life — something new about you every day.",
    lab: "AI spots patterns and suggests hypotheses — you test them with experiments on your own life.",
    insights: "All the key thoughts and realizations AI extracted from your entries.",
    people: "People from your entries: how often mentioned and in which entries.",
    projects: "Your projects gathered from entries, with all related notes.",
    biographer: "Ask your life — AI weaves an answer from all your entries. E.g. “Tell the story of my project” or “How did my health change?”.",
    intelligence: "AI finds causes, consequences and links of this entry to others — strictly from your data, no invention.",
    goals: "Yearly goals with progress. Add a goal and move the slider as you advance.",
    lifebook: "AI turns each month of your life into a chapter — themes and a flowing story.",
    energy: "How your energy changes and what lifts it.",
    sport: "All your entries about sport and workouts.",
    food: "Entries about food and nutrition.",
    family: "Moments and events with your family.",
    places: "Places from your entries — where you've been.",
    profile: "Your account: personal link, language, privacy, log out and delete account.",
  },
  uk: {
    today: "Головний екран: твої показники та записи за сьогодні. Можна додати запис тут або голосом у Telegram.",
    diary: "Усі записи за датами. Натисни на запис — побачиш повний AI-розбір.",
    tasks: "Усі твої завдання із записів в одному місці. Познач виконані галочкою.",
    wellness: "Здоров'я, енергія, спорт і харчування — все про тіло в одному місці.",
    plans: "Цілі, завдання та ідеї разом — плануй і нічого не втрачай.",
    health: "Сон, вага, самопочуття та тренди. Наповнюється, коли згадуєш здоров'я в записах.",
    analytics: "AI знаходить закономірності, відкриття та історію твого життя — щодня щось нове про тебе.",
    lab: "AI помічає закономірності й пропонує гіпотези — а ти перевіряєш їх експериментами над своїм життям.",
    insights: "Усі важливі думки та усвідомлення, які AI виділив із твоїх записів.",
    people: "Люди з записів: скільки разів згадані та в яких записах.",
    projects: "Твої проєкти, зібрані із записів, з усіма пов'язаними нотатками.",
    biographer: "Запитай своє життя — AI збере відповідь-історію з усіх твоїх записів. Напр.: «Розкажи історію проєкту».",
    intelligence: "AI знаходить причини, наслідки та зв'язки цього запису з іншими — строго за твоїми даними.",
    goals: "Цілі на рік із прогресом. Додавай ціль і рухай повзунок у міру виконання.",
    lifebook: "AI збирає кожен місяць твого життя у главу — з темами та зв'язною розповіддю.",
    energy: "Як змінюється твоя енергія і що її підвищує.",
    sport: "Усі записи про спорт і тренування.",
    food: "Записи про харчування та їжу.",
    family: "Моменти й події з сім'єю.",
    places: "Місця з твоїх записів — де ти бував.",
    profile: "Твій особистий кабінет: посилання, мова, приватність, вихід і видалення акаунта.",
  },
  fr: {
    today: "Ta journée en un coup d'œil : indicateurs et entrées du jour. Ajoute une entrée ici ou par la voix dans Telegram.",
    diary: "Toutes tes entrées par date. Touche une entrée pour voir l'analyse IA complète.",
    tasks: "Toutes tes tâches en un seul endroit. Coche-les quand c'est fait.",
    wellness: "Santé, énergie, sport et alimentation — tout sur ton corps au même endroit.",
    plans: "Objectifs, tâches et idées ensemble — planifie sans rien perdre.",
    health: "Sommeil, poids, bien-être et tendances. Se remplit quand tu mentionnes la santé.",
    analytics: "L'IA trouve des schémas, des découvertes et l'histoire de ta vie — du nouveau sur toi chaque jour.",
    lab: "L'IA repère des schémas et propose des hypothèses — tu les testes par des expériences sur ta vie.",
    insights: "Toutes les pensées clés que l'IA a extraites de tes entrées.",
    people: "Les personnes de tes entrées : fréquence et entrées associées.",
    projects: "Tes projets rassemblés depuis les entrées, avec toutes les notes liées.",
    biographer: "Interroge ta vie — l'IA tisse une réponse à partir de toutes tes entrées. Ex. : « Raconte l'histoire de mon projet ».",
    intelligence: "L'IA trouve causes, conséquences et liens de cette entrée — strictement à partir de tes données.",
    goals: "Objectifs annuels avec progression. Ajoute un objectif et déplace le curseur.",
    lifebook: "L'IA transforme chaque mois de ta vie en chapitre — thèmes et récit fluide.",
    energy: "Comment ton énergie évolue et ce qui la booste.",
    sport: "Toutes tes entrées sur le sport.",
    food: "Entrées sur l'alimentation.",
    family: "Moments et événements en famille.",
    places: "Les lieux de tes entrées — où tu es allé.",
    profile: "Ton compte : lien personnel, langue, confidentialité, déconnexion et suppression.",
  },
};

export function hints(locale: Locale): Record<string, string> {
  return H[locale] || H.ru;
}
