import type { Locale } from "./i18n";

const H: Record<Locale, Record<string, string>> = {
  ru: {
    notes: "Справочник, который не тонет в дневнике: коды, размеры, адреса, списки покупок. Спроси боту — ответит за секунду.",
    reminders: "Всё, о чём нельзя забыть, с датой и временем. Бот напишет сам в нужный момент, с кнопками «Готово» и «Через час».",
    sort: "Разбор сомнений: где AI не уверен, тот ли это человек или проект. Твоя поправка становится правилом, поэтому список должен пустеть.",
    trace: "Добрые дела, выполненные обещания и благодарности — то хорошее, что ты уже сделал, но не держишь в голове.",
    mood: "Календарь настроения по дням: заполняется сам из записей, но любой день можно поправить вручную.",
    paths: "Долгие дороги по шагам: год без сахара, ремонт, марафон. Каждая страница — веха, которой можно поделиться.",
    heirs: "Кому однажды откроется твоя Книга жизни. Назначаешь человека и условие — до него дневник остаётся только твоим.",
    referrals: "Кого ты привёл в LIFE OS — и кого пригласили они. Деревом, вглубь, с активностью каждого.",
    guide: "Все возможности по темам, с примерами фраз, и журнал изменений: что появилось на этой неделе.",
    ideas: "Твои предложения по LIFE OS и что с ними стало. Скажи боту «идея по LIFE OS» — он обсудит её с тобой, доведёт до постановки и передаст. О решении сообщит сам.",
    today: "Главный экран: твои показатели и записи за сегодня. Можно добавить запись прямо здесь или голосом в Telegram.",
    diary: "Все записи по датам. Нажми на запись — увидишь полный AI-разбор.",
    tasks: "Все твои задачи из записей в одном месте. Отмечай выполненные галочкой.",
    wellness: "Здоровье, энергия, спорт и питание — всё о теле в одном месте.",
    plans: "Цели, задачи и идеи вместе — планируй и ничего не теряй.",
    finance: "Простой учёт денег: записывай доходы и расходы, выбирай категорию — и сразу видишь баланс месяца и на что уходят деньги.",
    health: "Сон, вес, самочувствие и тренды. Наполняется, когда упоминаешь здоровье в записях.",
    analytics: "AI находит закономерности, открытия и историю твоей жизни — каждый день что-то новое о тебе.",
    lab: "AI замечает закономерности и предлагает гипотезы — а ты проверяешь их экспериментами над своей жизнью.",
    insights: "Все важные мысли и осознания, которые AI выделил из твоих записей.",
    people: "Твоя личная CRM отношений: люди из твоей жизни — кто, сколько раз упомянут и в каких записях. Чтобы не терять важных из виду.",
    projects: "Твои проекты, собранные из записей, со всеми связанными заметками.",
    biographer: "Спроси свою жизнь — AI соберёт ответ-историю из всех твоих записей. Например: «Расскажи историю проекта» или «Как менялось моё здоровье?».",
    wishlist: "Список желаний: вставь ссылку на товар — подтянем фото, название и цену. Поделись с друзьями, они тайно «забронируют» подарок — сюрприз сохранится.",
    books: "Твоя библиотека: что читаешь, хочешь и прочитал. Оценка, мини-ревью «зашла или нет», заметки и цитаты. Цель года, AI-советы и публичная страница для друзей.",
    intelligence: "AI находит причины, последствия и связи этой записи с другими — строго по твоим данным, без выдумок.",
    goals: "Цели на год с прогрессом. Добавляй цель и двигай ползунок по мере выполнения.",
    lifebook: "AI собирает каждый месяц твоей жизни в главу — с темами и связным рассказом.",
    knowledge: "Личная база знаний. Пришли боту ссылку на пост/reel Instagram или видео YouTube — AI вытащит суть (заголовок, ключевые мысли, теги) и сохранит сюда. Потом ищи по смыслу и возвращайся к идеям.",
    memory: "Визуальная память. Пришли боту или загрузи фото/документ (чек, гарантия, важный момент) — AI поймёт смысл, извлечёт данные и разложит по категориям. К фото можно добавить заметку голосом.",
    energy: "Как меняется твоя энергия и что её повышает.",
    sport: "Все записи про спорт и тренировки.",
    food: "Записи про питание и еду.",
    family: "Моменты и события с семьёй.",
    places: "Хронология твоих путешествий: поездки с фото и записями тех дней — и мечты, куда хочешь.",
    map: "Твоя жизнь на карте: точки из фотографий, соединённые по времени. Нажми на точку — увидишь снимок и свой комментарий к нему.",
    profile: "Твой личный кабинет: личная ссылка, язык, приватность, выход и удаление аккаунта.",
  },
  en: {
    notes: "A reference that does not drown in the diary: codes, sizes, addresses, shopping lists. Ask the bot and it answers in a second.",
    reminders: "Everything you must not forget, with a date and time. The bot writes to you at the right moment, with Done and In an hour.",
    sort: "Where AI is not sure whether it is the same person or project. Your correction becomes a rule, so the list should keep shrinking.",
    trace: "Good deeds, kept promises and gratitude — the good you have already done but do not keep in your head.",
    mood: "A mood calendar by day: filled in from your entries, and any day can be corrected by hand.",
    paths: "Long roads, step by step: a year without sugar, a renovation, a marathon. Every page is a milestone you can share.",
    heirs: "Who will one day be able to open your Book of Life. You name a person and a condition — until then the diary stays yours.",
    referrals: "Who you brought to LIFE OS — and who they invited. As a tree, in depth, with everyone's activity.",
    guide: "Every feature grouped by topic, with example phrases, plus a changelog of what appeared this week.",
    ideas: "Your suggestions for LIFE OS and what happened to them. Tell the bot “a LIFE OS idea” — it will talk it through with you, write it up and pass it on. You'll hear back about the decision.",
    today: "Your day at a glance: today's metrics and entries. Add an entry here or by voice in Telegram.",
    diary: "All your entries by date. Tap an entry to see the full AI breakdown.",
    tasks: "All your tasks from entries in one place. Tick them off when done.",
    wellness: "Health, energy, sport and food — all about your body in one place.",
    plans: "Goals, tasks and ideas together — plan and lose nothing.",
    finance: "Simple money tracking: log income and expenses, pick a category — and instantly see your monthly balance and where the money goes.",
    health: "Sleep, weight, wellbeing and trends. Fills in as you mention health in entries.",
    analytics: "AI finds patterns, discoveries and the story of your life — something new about you every day.",
    lab: "AI spots patterns and suggests hypotheses — you test them with experiments on your own life.",
    insights: "All the key thoughts and realizations AI extracted from your entries.",
    people: "Your personal relationship CRM: the people in your life — who, how often mentioned and in which entries. So you never lose the important ones.",
    projects: "Your projects gathered from entries, with all related notes.",
    biographer: "Ask your life — AI weaves an answer from all your entries. E.g. “Tell the story of my project” or “How did my health change?”.",
    wishlist: "Wishlist: paste a product link — we'll pull the photo, title and price. Share with friends; they secretly reserve a gift so the surprise stays.",
    books: "Your library: what you're reading, want to read and have read. Rating, a quick “loved it or not” review, notes and quotes. Year goal, AI picks and a public page for friends.",
    intelligence: "AI finds causes, consequences and links of this entry to others — strictly from your data, no invention.",
    goals: "Yearly goals with progress. Add a goal and move the slider as you advance.",
    lifebook: "AI turns each month of your life into a chapter — themes and a flowing story.",
    knowledge: "Your personal knowledge base. Send the bot an Instagram post/reel or YouTube link — AI extracts the gist (title, key points, tags) and saves it here. Then search by meaning and revisit ideas.",
    memory: "Visual memory. Send or upload a photo/document (receipt, warranty, a moment) — AI understands it, extracts the details and files it by category. You can add a note by voice.",
    energy: "How your energy changes and what lifts it.",
    sport: "All your entries about sport and workouts.",
    food: "Entries about food and nutrition.",
    family: "Moments and events with your family.",
    places: "Your travel timeline: trips with photos and entries from those days — plus dream destinations.",
    map: "Your life on a map: points from your photos, connected in time. Tap a point to see the shot and your own comment on it.",
    profile: "Your account: personal link, language, privacy, log out and delete account.",
  },
  uk: {
    notes: "Довідник, який не тоне в щоденнику: коди, розміри, адреси, списки покупок. Спитай бота — відповість за секунду.",
    reminders: "Усе, про що не можна забути, з датою й часом. Бот напише сам у потрібну мить, із кнопками «Готово» і «Через годину».",
    sort: "Розбір сумнівів: де AI не впевнений, чи та сама це людина або проєкт. Твоя поправка стає правилом, тому список має порожніти.",
    trace: "Добрі справи, виконані обіцянки й подяки — те добре, що ти вже зробив, але не тримаєш у голові.",
    mood: "Календар настрою по днях: заповнюється сам із записів, але будь-який день можна поправити вручну.",
    paths: "Довгі дороги по кроках: рік без цукру, ремонт, марафон. Кожна сторінка — віха, якою можна поділитися.",
    heirs: "Кому колись відкриється твоя Книга життя. Призначаєш людину та умову — до того щоденник лишається тільки твоїм.",
    referrals: "Кого ти привів у LIFE OS — і кого запросили вони. Деревом, углиб, з активністю кожного.",
    guide: "Усі можливості за темами, з прикладами фраз, і журнал змін: що додалося цього тижня.",
    ideas: "Твої пропозиції щодо LIFE OS і що з ними сталося. Скажи боту «ідея по LIFE OS» — він обговорить її з тобою і передасть. Про рішення повідомить сам.",
    today: "Головний екран: твої показники та записи за сьогодні. Можна додати запис тут або голосом у Telegram.",
    diary: "Усі записи за датами. Натисни на запис — побачиш повний AI-розбір.",
    tasks: "Усі твої завдання із записів в одному місці. Познач виконані галочкою.",
    wellness: "Здоров'я, енергія, спорт і харчування — все про тіло в одному місці.",
    plans: "Цілі, завдання та ідеї разом — плануй і нічого не втрачай.",
    finance: "Простий облік грошей: записуй доходи й витрати, обирай категорію — і одразу бачиш баланс місяця та на що йдуть гроші.",
    health: "Сон, вага, самопочуття та тренди. Наповнюється, коли згадуєш здоров'я в записах.",
    analytics: "AI знаходить закономірності, відкриття та історію твого життя — щодня щось нове про тебе.",
    lab: "AI помічає закономірності й пропонує гіпотези — а ти перевіряєш їх експериментами над своїм життям.",
    insights: "Усі важливі думки та усвідомлення, які AI виділив із твоїх записів.",
    people: "Твоя особиста CRM стосунків: люди з твого життя — хто, скільки разів згаданий і в яких записах. Щоб не втрачати важливих із поля зору.",
    projects: "Твої проєкти, зібрані із записів, з усіма пов'язаними нотатками.",
    biographer: "Запитай своє життя — AI збере відповідь-історію з усіх твоїх записів. Напр.: «Розкажи історію проєкту».",
    wishlist: "Список бажань: встав посилання на товар — підтягнемо фото, назву й ціну. Поділись із друзями, вони таємно «забронюють» подарунок — сюрприз збережеться.",
    books: "Твоя бібліотека: що читаєш, хочеш і прочитав. Оцінка, міні-рецензія «зайшла чи ні», нотатки й цитати. Ціль року, AI-поради та публічна сторінка для друзів.",
    intelligence: "AI знаходить причини, наслідки та зв'язки цього запису з іншими — строго за твоїми даними.",
    goals: "Цілі на рік із прогресом. Додавай ціль і рухай повзунок у міру виконання.",
    lifebook: "AI збирає кожен місяць твого життя у главу — з темами та зв'язною розповіддю.",
    knowledge: "Особиста база знань. Надішли боту посилання на допис/reel Instagram або відео YouTube — AI витягне суть (заголовок, ключові думки, теги) і збереже сюди. Потім шукай за змістом і повертайся до ідей.",
    memory: "Візуальна пам'ять. Надішли або завантаж фото/документ (чек, гарантія, важливий момент) — AI зрозуміє суть, витягне дані й розкладе за категоріями. До фото можна додати нотатку голосом.",
    energy: "Як змінюється твоя енергія і що її підвищує.",
    sport: "Усі записи про спорт і тренування.",
    food: "Записи про харчування та їжу.",
    family: "Моменти й події з сім'єю.",
    places: "Хронологія твоїх подорожей: поїздки з фото і записами тих днів — і мрії, куди хочеш.",
    map: "Твоє життя на карті: точки з фотографій, з'єднані за часом. Натисни на точку — побачиш знімок і свій коментар.",
    profile: "Твій особистий кабінет: посилання, мова, приватність, вихід і видалення акаунта.",
  },
  fr: {
    notes: "Un aide-mémoire qui ne se noie pas dans le journal : codes, tailles, adresses, listes de courses. Demande au bot, il répond aussitôt.",
    reminders: "Tout ce qu'il ne faut pas oublier, avec date et heure. Le bot t'écrit au bon moment, avec Fait et Dans une heure.",
    sort: "Là où l'IA hésite : même personne ou non, même projet ou non. Ta correction devient une règle, la liste se vide peu à peu.",
    trace: "Bonnes actions, promesses tenues et gratitudes — le bien que tu as déjà fait sans le garder en tête.",
    mood: "Un calendrier d'humeur au jour le jour : rempli depuis tes notes, corrigeable à la main.",
    paths: "Les longs chemins, étape par étape : un an sans sucre, des travaux, un marathon. Chaque page est un jalon partageable.",
    heirs: "Qui pourra un jour ouvrir ton Livre de vie. Tu désignes une personne et une condition ; avant, le journal reste le tien.",
    referrals: "Qui tu as amené sur LIFE OS — et qui eux ont invité. En arbre, en profondeur, avec l'activité de chacun.",
    guide: "Toutes les fonctions par thème, avec des exemples, et le journal des nouveautés de la semaine.",
    ideas: "Tes propositions pour LIFE OS et ce qu'elles sont devenues. Dis au bot « une idée pour LIFE OS » : il en discute avec toi, la met au propre et la transmet.",
    today: "Ta journée en un coup d'œil : indicateurs et entrées du jour. Ajoute une entrée ici ou par la voix dans Telegram.",
    diary: "Toutes tes entrées par date. Touche une entrée pour voir l'analyse IA complète.",
    tasks: "Toutes tes tâches en un seul endroit. Coche-les quand c'est fait.",
    wellness: "Santé, énergie, sport et alimentation — tout sur ton corps au même endroit.",
    plans: "Objectifs, tâches et idées ensemble — planifie sans rien perdre.",
    finance: "Suivi simple de l'argent : note tes revenus et dépenses, choisis une catégorie — et vois aussitôt ton solde du mois et où part l'argent.",
    health: "Sommeil, poids, bien-être et tendances. Se remplit quand tu mentionnes la santé.",
    analytics: "L'IA trouve des schémas, des découvertes et l'histoire de ta vie — du nouveau sur toi chaque jour.",
    lab: "L'IA repère des schémas et propose des hypothèses — tu les testes par des expériences sur ta vie.",
    insights: "Toutes les pensées clés que l'IA a extraites de tes entrées.",
    people: "Ton CRM relationnel personnel : les gens de ta vie — qui, combien de fois mentionnés et dans quelles entrées. Pour ne pas perdre les importants de vue.",
    projects: "Tes projets rassemblés depuis les entrées, avec toutes les notes liées.",
    biographer: "Interroge ta vie — l'IA tisse une réponse à partir de toutes tes entrées. Ex. : « Raconte l'histoire de mon projet ».",
    wishlist: "Liste de souhaits : colle un lien produit — on récupère la photo, le titre et le prix. Partage-la ; tes amis réservent un cadeau en secret, la surprise reste.",
    books: "Ta bibliothèque : ce que tu lis, veux lire et as lu. Note, mini-avis « aimé ou pas », notes et citations. Objectif de l'année, suggestions IA et page publique pour tes amis.",
    intelligence: "L'IA trouve causes, conséquences et liens de cette entrée — strictement à partir de tes données.",
    goals: "Objectifs annuels avec progression. Ajoute un objectif et déplace le curseur.",
    lifebook: "L'IA transforme chaque mois de ta vie en chapitre — thèmes et récit fluide.",
    knowledge: "Ta base de connaissances. Envoie au bot un lien Instagram (post/reel) ou YouTube — l'IA en extrait l'essentiel (titre, points clés, tags) et l'enregistre ici. Ensuite, recherche par sens et retrouve tes idées.",
    memory: "Mémoire visuelle. Envoie ou téléverse une photo/document (reçu, garantie, un moment) — l'IA le comprend, en extrait les détails et le classe par catégorie. Tu peux ajouter une note par la voix.",
    energy: "Comment ton énergie évolue et ce qui la booste.",
    sport: "Toutes tes entrées sur le sport.",
    food: "Entrées sur l'alimentation.",
    family: "Moments et événements en famille.",
    places: "La chronologie de tes voyages : séjours avec photos et entrées de ces jours — et tes destinations de rêve.",
    map: "Ta vie sur une carte : des points issus de tes photos, reliés dans le temps. Touche un point pour voir la photo et ton commentaire.",
    profile: "Ton compte : lien personnel, langue, confidentialité, déconnexion et suppression.",
  },
  es: {
    notes: "Un cuaderno de datos que no se pierde en el diario: códigos, medidas, direcciones, listas. Pregunta al bot y responde al instante.",
    reminders: "Todo lo que no puedes olvidar, con fecha y hora. El bot te escribe en el momento justo, con Hecho y En una hora.",
    sort: "Donde la IA duda: si es la misma persona o el mismo proyecto. Tu corrección se vuelve regla, así que la lista debe vaciarse.",
    trace: "Buenas acciones, promesas cumplidas y gratitudes — el bien que ya hiciste y no llevas en la cabeza.",
    mood: "Un calendario de ánimo por días: se rellena desde tus entradas y cualquier día se puede corregir a mano.",
    paths: "Caminos largos, paso a paso: un año sin azúcar, una reforma, un maratón. Cada página es un hito que puedes compartir.",
    heirs: "Quién podrá abrir algún día tu Libro de vida. Eliges persona y condición; hasta entonces el diario es solo tuyo.",
    referrals: "A quién trajiste a LIFE OS — y a quién invitaron ellos. En árbol, en profundidad, con la actividad de cada uno.",
    guide: "Todas las funciones por temas, con frases de ejemplo, y el registro de novedades de la semana.",
    ideas: "Tus propuestas para LIFE OS y en qué quedaron. Dile al bot «una idea para LIFE OS»: lo hablará contigo, lo redactará y lo pasará.",
    today: "Tu día de un vistazo: tus indicadores y entradas de hoy. Añade una entrada aquí o por voz en Telegram.",
    diary: "Todas tus entradas por fecha. Toca una entrada para ver el análisis completo de la IA.",
    tasks: "Todas tus tareas de las entradas en un solo lugar. Márcalas al terminarlas.",
    wellness: "Salud, energía, deporte y comida — todo sobre tu cuerpo en un solo lugar.",
    plans: "Metas, tareas e ideas juntas — planifica sin perder nada.",
    finance: "Control simple del dinero: registra ingresos y gastos, elige una categoría — y ve al instante tu balance del mes y en qué se va el dinero.",
    health: "Sueño, peso, bienestar y tendencias. Se completa cuando mencionas la salud en tus entradas.",
    analytics: "La IA encuentra patrones, descubrimientos e historia de tu vida — algo nuevo sobre ti cada día.",
    lab: "La IA detecta patrones y propone hipótesis — tú las pruebas con experimentos en tu propia vida.",
    insights: "Todos los pensamientos clave y las realizaciones que la IA extrajo de tus entradas.",
    people: "Tu CRM personal de relaciones: las personas de tu vida — quién, cuántas veces se menciona y en qué entradas. Para no perder de vista a los importantes.",
    projects: "Tus proyectos reunidos de las entradas, con todas las notas relacionadas.",
    biographer: "Pregúntale a tu vida — la IA teje una respuesta a partir de todas tus entradas. Por ejemplo: «Cuéntame la historia de mi proyecto» o «¿Cómo cambió mi salud?».",
    wishlist: "Lista de deseos: pega el enlace de un producto — recuperamos la foto, el título y el precio. Compártela con amigos, ellos «reservan» un regalo en secreto — la sorpresa se mantiene.",
    books: "Tu biblioteca: qué lees, qué quieres leer y qué has leído. Calificación, una mini reseña «me gustó o no», notas y citas. Meta del año, sugerencias de la IA y una página pública para amigos.",
    intelligence: "La IA encuentra causas, consecuencias y vínculos de esta entrada con otras — estrictamente a partir de tus datos, sin inventar.",
    goals: "Metas anuales con progreso. Añade una meta y mueve el control deslizante según avances.",
    lifebook: "La IA convierte cada mes de tu vida en un capítulo — con temas y un relato fluido.",
    knowledge: "Tu base de conocimiento personal. Envía al bot un enlace de post/reel de Instagram o video de YouTube — la IA extrae lo esencial (título, ideas clave, etiquetas) y lo guarda aquí. Luego busca por significado y retoma tus ideas.",
    memory: "Memoria visual. Envía o sube una foto/documento (recibo, garantía, un momento) — la IA entiende el sentido, extrae los datos y los clasifica por categoría. Puedes añadir una nota por voz a la foto.",
    energy: "Cómo cambia tu energía y qué la eleva.",
    sport: "Todas tus entradas sobre deporte y entrenamientos.",
    food: "Entradas sobre alimentación y comida.",
    family: "Momentos y eventos con la familia.",
    places: "Lugares donde has estado, y adónde sueñas con ir.",
    map: "Tu vida en un mapa: puntos de tus fotos, unidos en el tiempo. Toca un punto para ver la foto y tu comentario.",
    profile: "Tu cuenta: enlace personal, idioma, privacidad, cerrar sesión y eliminar la cuenta.",
  },
};

export function hints(locale: Locale): Record<string, string> {
  return H[locale] || H.ru;
}
